package interpreter.lexer;

public enum TokenType {
    KEYWORD, IDENTIFIER, NUMBER, ARITHMETIC_OPERATOR, WHITESPACE, QUOTATION_MARK, PARENTHESES, BRACE, SEMI_COLON, STRING,
    MODIFIER, TYPE, SQUARE_BRACKET, COMMA, DOT, NewLine, Ampersand, ASSIGNMENT, BOOLEAN_OPERATOR, GOTO_IF_FALSE, GOTO,

    Boolean, UNKNOWN
}
